stages:
  - build
  - release

default:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  tags:
    - wopr
  before_script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json

release:
  stage: release
  image: registry.mdcatapult.io/informatics/docker-images/ci/golang
  script:
    - release.sh
  only:
    refs:
      - master
  except:
    - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

build-dictionary-dev:
  stage: build
  script:
    - |
      /kaniko/executor \
      --context $CI_PROJECT_DIR \
      --destination $CI_REGISTRY_IMAGE/dictionary:$CI_COMMIT_REF_SLUG
      --dockerfile $CI_PROJECT_DIR/go/cmd/dictionary/Dockerfile
  except:
    refs:
      - master
      - tags
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

build-dictionary-master:
  stage: build
  script:
    - |
      /kaniko/executor \
      --context $CI_PROJECT_DIR \
      --destination $CI_REGISTRY_IMAGE/dictionary:$CI_COMMIT_REF_SLUG
      --destination $CI_REGISTRY_IMAGE/dictionary:latest
      --dockerfile $CI_PROJECT_DIR/go/cmd/dictionary/Dockerfile
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/


build-regexer-dev:
  stage: build
  script:
    - |
      /kaniko/executor \
      --context $CI_PROJECT_DIR \
      --destination $CI_REGISTRY_IMAGE/regexer:$CI_COMMIT_REF_SLUG
      --dockerfile $CI_PROJECT_DIR/go/cmd/regexer/Dockerfile
  except:
    refs:
      - master
      - tags
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

build-regexer-master:
  stage: build
  script:
    - |
      /kaniko/executor \
      --context $CI_PROJECT_DIR \
      --destination $CI_REGISTRY_IMAGE/regexer:$CI_COMMIT_REF_SLUG
      --destination $CI_REGISTRY_IMAGE/regexer:latest
      --dockerfile $CI_PROJECT_DIR/go/cmd/regexer/Dockerfile
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/


build-dictionary-init-dev:
  stage: build
  script:
    - |
      /kaniko/executor \
      --context $CI_PROJECT_DIR \
      --destination $CI_REGISTRY_IMAGE/dictionary-init:$CI_COMMIT_REF_SLUG
      --dockerfile $CI_PROJECT_DIR/go/cmd/dictionary-init/Dockerfile
  except:
    refs:
      - master
      - tags
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

build-dictionary-init-master:
  stage: build
  script:
    - |
      /kaniko/executor \
      --context $CI_PROJECT_DIR \
      --destination $CI_REGISTRY_IMAGE/dictionary-init:$CI_COMMIT_REF_SLUG
      --destination $CI_REGISTRY_IMAGE/dictionary-init:latest
      --dockerfile $CI_PROJECT_DIR/go/cmd/dictionary-init/Dockerfile
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/


build-rest-api-dev:
  stage: build
  script:
    - |
      /kaniko/executor \
      --context $CI_PROJECT_DIR \
      --destination $CI_REGISTRY_IMAGE/rest-api:$CI_COMMIT_REF_SLUG
      --dockerfile $CI_PROJECT_DIR/go/cmd/rest-api/Dockerfile
  except:
    refs:
      - master
      - tags
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

build-rest-api-master:
  stage: build
  script:
    - |
      /kaniko/executor \
      --context $CI_PROJECT_DIR \
      --destination $CI_REGISTRY_IMAGE/rest-api:$CI_COMMIT_REF_SLUG
      --destination $CI_REGISTRY_IMAGE/rest-api:latest
      --dockerfile $CI_PROJECT_DIR/go/cmd/rest-api/Dockerfile
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

