version: "3.8"
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  elasticsearch:
    image: elasticsearch:7.13.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node