# case- insensitive list of words to blacklist. Capitalised versions of words such as 'via' are
# synonyms of genes and therefore should not be caught by this list.
entities:
  - proteins
  - protein
  - hub
  - via
  - tgn
  - alternative name
  - orf
  - golgi
  - golgi apparatus
  - ptm
  - vps
  - mass
  - truncated n- terminus
  - et
  - van
  - cell
  - transmembrane proteins
  - killer
  - pdz domain
  - step
  - coil
  - virion assembly
  - oct
  - amigo
  - sera
  - peptide 1
  - peptide 2
  - dec
  - bs8
  - spatial
  - mice
  - fast
  - damage
  - wave
  - nat
  - med
  - annu
  - proc
  - traits
  - sino
  - tele
  - aid
  - yeast
  - ubiquitin- like protein
  - tip
  - impact
  - top
  - star
  - stars
  - enigma
  - max
  - bar
  - bars
  - phd
  - soc
  - sur
  - sbi
  - trap
  - traps
  - fig
  - bright
  - fate
  - sharp
  - chip
  - flash
  - light
  - lab
  - past
  - intracellular protein
  - mark
  - kit
  - prism
  - minor
  - prep
  - degs
  - mix
  - acta
  - map
  - scott
  - lind

# some capitalised words are abbreviations and definitely not genes. These should be blacklisted.
abbreviations:
  - S1A
  - S1B
  - S1C
  - S1D
  - S1E
  - S1F
  - S2A
  - S2B
  - S2C
  - S2D
  - S2E
  - S2F
  - S3A
  - S3B
  - S3C
  - S3D
  - S3E
  - S3F
  - S4A
  - S4B
  - S4C
  - S4D
  - S4E
  - S4F
  - S5A
  - S5B
  - S5C
  - S5D
  - S5E
  - S5F
  - S6A
  - S6B
  - S6C
  - S6D
  - S6E
  - S6F
  - S1
  - S2
  - S3
  - S4
  - S5
  - S6
  - S7
  - S8
  - S9
  - S10
  - S11
  - S12
  - S13
  - S14
  - S15
  - S16
  - P0
  - PTM
  - SNX

entity_groups:
  - gene or protein class
