log_level: info
dictionary:
  name: "pubchem_synonyms"
  path: ./go/cmd/dictionary-importer/dictionaries/test.tsv # this should be pubchem.tsv for the existing tests!!
  format: "leadmine" # this should be pubchem for the existing tests!!!!
backend_database: redis
pipeline_size: 10000