server:
  http_port: 8080

blacklist: config/blacklists/global.yml

grpc_recognisers:
  # The keys in this object will become recognition api query parameters.
  # i.e. to use this recogniser, do http://localhost:8080/html/entities?recogniser=dictionary
  dictionary:
    host: localhost
    port: 50051
  regexer:
    host: localhost
    port: 50052
#  iupac:
#    host: localhost
#    port: 50054

http_recognisers:
  leadmine-chemical-entities:
    type: leadmine
    url: https://leadmine.wopr.inf.mdc/chemical-entities/entities
    blacklist: config/blacklists/leadmine-chemical-entities.yml

  leadmine-proteins:
    type: leadmine
    url: https://leadmine.wopr.inf.mdc/proteins/entities
    blacklist: config/blacklists/leadmine-proteins.yml

  leadmine-disease:
    type: leadmine
    url: https://leadmine.wopr.inf.mdc/diseases/entities



