server:
  http_port: 8080

grpc_recognisers:
  dictionary:
    host: localhost
    port: 50051
  regexer:
    host: localhost
    port: 50052
#  iupac:
#    host: localhost
#    port: 50054

http_recognisers:
  leadmine-chemical-entities:
    type: leadmine
    url: https://leadmine.wopr.inf.mdc/chemical-entities/entities

    leadmine-proteins:
      type: leadmine
      url: https://leadmine.wopr.inf.mdc/proteins/entities
