server:
  http_port: 8080

grpc_recognisers:
  dictionary:
    host: localhost
    port: 50051
  regexer:
    host: localhost
    port: 50052
#  iupac:
#    host: localhost
#    port: 50054

http_recognisers:
  dummy:
    type: dummy