chebi: 'CHEBI:\d+'
chembl: 'CHEMBL\d+'
clinical_trials: 'NCT\d{8}'
dbsnp: 'rs\d+'
drugbank: 'DB\d{5}'
ensembl: 'ENS(MUS)?[EGPRT]\d{11}(\.\d+)?'
evidence_code_ontology: 'ECO:\d{7}'
gene_ontology: 'GO:\d{7}'
hgnc: '(HGNC|hgnc):\d{1,5}'
hmdb: 'HMDB\d+'
interpro: 'IPR\d{6}'
kegg: '[CD]\d{5}'
mesh: '[CD]\d{6}'
pfam: 'PF\d{5}'
pubmed_central: 'PMC\d+'
reactome: 'R-[A-Z]{3}-\d+(-\d+)?(\.\d+)?|REACT_\d+(\.\d+)?'
refseq: '((AC|AP|NC|NG|NM|NP|NR|NT|NW|XM|XP|XR|YP|ZP)_\d+|(NZ_[A-Z]{4}\d+))(\.\d+)?'
uniparc: 'UPI[A-F0-9]{10}'
uniprot: '([A-NR-Z][0-9]([A-Z][A-Z0-9]{2}[0-9]){1,2})|([OPQ][0-9][A-Z0-9]{3}[0-9])(\.\d+)?'
zinc: 'ZINC\d+'